VCKOH:
  Creator: Min3CraftDud3
  WebSite: http://www.SinfulPixel.com
  Capture_Radius_Blocks: 15
  Capture_Time_Mins: 15
  Game_TimeOut_Hrs: 1
  Times: #Time is on a 24 hour clock, only way to do it without massive amounts of pointless code.
  - 00:00
  - 04:00
  - 08:00
  - '12:00'
  - '16:00'
  - '20:00'
  Locations: #Create a point then delete the default values.
  - world,-100,100,500 #delete
  - world,100,75,350 #delete
  - world,100,100,100 #delete
  - world,274,4,394 #delete
  - world,266,4,393 #delete
 
