name: VCKOH
main: com.SinfulPixel.VCKOH.VCKOH
version: 1.3
description: King Of The Hill Plugin for VCGAMING.NET
author: Min3CraftDud3
website: http://www.SinfulPixel.com
commands:
  KOTH:
    description: "Base Command"